version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      non-breaking:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
